# Generated by Django 3.2 on 2022-11-07 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_signup_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 7, 23, 15, 0, 413268)),
        ),
    ]
