# Generated by Django 3.2 on 2022-11-07 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_signup_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 18, 19, 54, 136142, tzinfo=utc)),
        ),
    ]
